package org.vaadin.textfieldformatter.demo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
public class DemoLayout extends VerticalLayout {
	protected TextField creditCardField;
	protected CodeSample creditCardCode;
	protected TextField numeralField;
	protected CodeSample numeralCode;
	protected TextField customNumeralField;
	protected CodeSample customNumeralCode;
	protected TextField blocksField;
	protected CodeSample blocksCode;
	protected TextField numericField;
	protected CodeSample numericCode;
	protected TextField delimitersField;
	protected CodeSample delimitersCode;
	protected TextField prefixField;
	protected CodeSample prefixCode;

	public DemoLayout() {
		Design.read(this);
	}
}
